# Generated by Django 4.2.20 on 2025-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('installation', 'Installation'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SoldEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('sale_date', models.DateField()),
            ],
        ),
    ]
