# Generated by Django 4.2.20 on 2025-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_type',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('garantia', 'Garantia'), ('Pip', 'pip'), ('interno', 'Interno')], max_length=20),
        ),
    ]
