# Generated by Django 4.2.20 on 2025-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0002_alter_servicerecord_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldequipment',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
