# Generated by Django 4.2.20 on 2025-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0003_soldequipment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldequipment',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='soldequipment',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
