# Generated by Django 3.2.25 on 2025-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pops', '0006_auto_20250421_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='revenue',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='soldequipment',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soldequipment',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soldequipment',
            name='serial_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
